services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./core:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: shumma
      POSTGRES_PASSWORD: Xx0922247.
      POSTGRES_DB: gestion_mangas
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: